#!/bin/sh

DAEMON=/usr/bin/telemetry_client
TELEMETRY_PID=/var/run/telemetry.pid


case "$1" in
    start)
        [ -f $TELEMETRY_PID ] && exit 0

        printf "Starting telemetry: "
        start-stop-daemon -S -q -b -m -p $TELEMETRY_PID -x $DAEMON
        if [ $? = 0 ]
        then
            echo "OK"
        else
            [ -f $TELEMETRY_PID ] && rm $TELEMETRY_PID
            echo "FAIL"
        fi
        ;;
    stop)
        printf "Stopping telemetry: "
        if start-stop-daemon -K --oknodo -p $TELEMETRY_PID > /dev/null; then
            rm "$TELEMETRY_PID" 2>/dev/null
            echo "OK"
        else
            echo "FAIL"
        fi
        ;;
    restart|reload)
        $0 stop
        /bin/sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
