#!/bin/sh

CONF_PATH=/etc/librarian.ini
LIBRARIAN_PID=/var/run/librarian.pid
LIBRARIAN_DATA=/mnt/data/librarian
LIBRARIAN_LOG_DIR=/mnt/data/log
DAEMON="librarian --conf $CONF_PATH"

case "$1" in
    start)
        [ ! -f $LIBRARIAN_PID ] || exit 0
        mkdir -p $LIBRARIAN_DATA
        mkdir -p $LIBRARIAN_LOG_DIR
        printf "Starting librarian: "
        $DAEMON > /dev/null 2>&1 &
        if [ $? ]; then
            echo $! > $LIBRARIAN_PID
            echo "OK"
        else
            echo "FAILED"
        fi
        ;;
    stop)
        if [ -f $LIBRARIAN_PID ] ; then
            printf "Stopping librarian: "
            kill "$(cat $LIBRARIAN_PID)"
            rm $LIBRARIAN_PID
            echo "OK"
        fi
        ;;
    restart|reload)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit $?
