#!/bin/sh

PID_FILE=/var/run/ondd.pid
CACHE_PATH=%CACHEDIR%
MAIN_STORAGE=%INTERNALDIR%
EXT_STORAGE=%EXTERNALDIR%
ONDD_GROUP=%GROUP%
ONDD_TIMEOUT_HANDLER=/usr/sbin/ontimeout
ONDD_SDR_TIMEOUT=60  # seconds
ONDD_EXTRA_ARGS=

if [ -x "$ONDD_TIMEOUT_HANDLER" ]; then
  ONDD_EXTRA_ARGS="--sdr-timeout-handler $ONDD_TIMEOUT_HANDLER --sdr-timeout $ONDD_SDR_TIMEOUT"
fi

ONDD_ARGS="-d --pid-file $PID_FILE -c $CACHE_PATH -o $output_path $ONDD_EXTRA_ARGS"

start() {
  mkdir -p "$CACHE_PATH"
  mkdir -p "$MAIN_STORAGE"
  mkdir -p "$EXT_STORAGE"
  for storage in $MAIN_STORAGE $EXT_STORAGE; do
      chgrp "$ONDD_GROUP" "$storage"
      chmod g+ws "$storage"
  done

  if mount | grep "$EXT_STORAGE" >/dev/null 2>&1; then
    output_path=$EXT_STORAGE
  else
    output_path=$MAIN_STORAGE
  fi

  printf "Starting ondd: "
  start-stop-daemon -S -q -p $PID_FILE --exec /usr/sbin/ondd -- $ONDD_ARGS
  if [ $? ]; then
    echo "OK"
  else
    echo "FAILED"
  fi
}

stop() {
  printf "Stopping ondd: "
  start-stop-daemon -K -q -p $PID_FILE
  [ -f $PID_FILE ] && rm $PID_FILE
  echo "OK"
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    stop
    sleep 1
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload}"
    exit 1
esac

exit $?
