#!/bin/sh

CONF_PATH=/etc/fsal.ini
FSAL_PID=/var/run/fsal.pid
FSAL_LOG_DIR=/mnt/data/log
DAEMON="fsal-daemon --pid-file $FSAL_PID --conf $CONF_PATH"

case "$1" in
    start)
        [ ! -f $FSAL_PID ] || exit 0
        mkdir -p "$FSAL_LOG_DIR"
        printf "Starting fsal: "
        $DAEMON > /dev/null 2>&1 &
        if [ $? ]; then
            echo "OK"
        else
            echo "FAILED"
        fi
        ;;
    stop)
        if [ -f $FSAL_PID ] ; then
            printf "Stopping fsal: "
            kill "$(cat $FSAL_PID)"
            echo "OK"
        fi
        ;;
    restart|reload)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit $?
